name: CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/runner-images/issues/13046
          - os: macos-14
            triple: aarch64-apple-darwin
          - os: macos-15-intel
            triple: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.87.0
      - uses: lukka/get-cmake@v3.27.4

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.11
          check-latest: true

      - name: Show rust version
        run: |
          cargo version
          rustup toolchain list

      - name: Check out succinctlabs/rust
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          path: rust
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Check out succinctlabs/sp1
        uses: actions/checkout@v3
        with:
          repository: succinctlabs/sp1
          ref: xuejie/build-rv64-library-target
          path: sp1

      - name: Build
        run: |
          cd sp1/crates/cli
          GITHUB_ACTIONS=false SP1_BUILD_DIR=$GITHUB_WORKSPACE cargo run --bin cargo-prove -- prove build-toolchain

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: rust-toolchain-${{ matrix.triple }}
          path: sp1/crates/cli/rust-toolchain-${{ matrix.triple }}.tar.gz

  build-runs-on:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: 32cpu-linux-arm64
            image: ubuntu22-full-arm64
            triple: aarch64-unknown-linux-gnu
          - runner: 32cpu-linux-x64
            image: ubuntu22-full-x64
            triple: x86_64-unknown-linux-gnu
    runs-on: [runs-on, "runner=${{ matrix.runner }}", "image=${{ matrix.image }}", disk=large, "run-id=${{ github.run_id }}"]
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.87.0
      - uses: lukka/get-cmake@v3.27.4

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.11
          check-latest: true

      - name: Show rust version
        run: |
          cargo version
          rustup toolchain list

      - name: Check out succinctlabs/rust
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          path: rust
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Check out succinctlabs/sp1
        uses: actions/checkout@v3
        with:
          repository: succinctlabs/sp1
          ref: xuejie/build-rv64-library-target
          path: sp1

      - name: Build
        run: |
          cd sp1/crates/cli
          GITHUB_ACTIONS=false SP1_BUILD_DIR=$GITHUB_WORKSPACE cargo run --bin cargo-prove -- prove build-toolchain

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: rust-toolchain-${{ matrix.triple }}
          path: sp1/crates/cli/rust-toolchain-${{ matrix.triple }}.tar.gz
